
name: app-funcionarios

services:
  postgres:
    image: postgres:16
    container_name: app-funcionarios-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bd-funcionarios
      POSTGRES_USER: coti
      POSTGRES_PASSWORD: coti
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coti -d bd-funcionarios"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: app-funcionarios-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: coti@email.com
      PGADMIN_DEFAULT_PASSWORD: Coti@2026
    ports:
      - "5051:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:


  